export enum AuditAction {
  // General actions
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  EXPORT = 'EXPORT',

  // Authentication actions
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Member actions
  MEMBER_CREATED = 'MEMBER_CREATED',
  MEMBER_UPDATED = 'MEMBER_UPDATED',
  MEMBER_DELETED = 'MEMBER_DELETED',
  MEMBER_STATUS_CHANGED = 'MEMBER_STATUS_CHANGED',

  // Inventory actions
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_ITEM_DELETED = 'INVENTORY_ITEM_DELETED',
  INVENTORY_STOCK_ADDED = 'INVENTORY_STOCK_ADDED',
  INVENTORY_STOCK_REMOVED = 'INVENTORY_STOCK_REMOVED',
  INVENTORY_ITEM_TRANSFERRED = 'INVENTORY_ITEM_TRANSFERRED',

  // Group/Unit actions
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_UPDATED = 'GROUP_UPDATED',
  GROUP_MEMBER_ADDED = 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED = 'GROUP_MEMBER_REMOVED',

  // Report actions
  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_DOWNLOADED = 'REPORT_DOWNLOADED',

  // Bulk operations
  BULK_IMPORT = 'BULK_IMPORT',
  BULK_UPDATE = 'BULK_UPDATE',
  BULK_DELETE = 'BULK_DELETE',

  // Event actions
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_DELETED = 'EVENT_DELETED',
  EVENT_REGISTRATION_CREATED = 'EVENT_REGISTRATION_CREATED',
  EVENT_REGISTRATION_UPDATED = 'EVENT_REGISTRATION_UPDATED',
  EVENT_CHECK_IN = 'EVENT_CHECK_IN',

  // Library actions
  BOOK_CREATED = 'BOOK_CREATED',
  BOOK_UPDATED = 'BOOK_UPDATED',
  BOOK_DELETED = 'BOOK_DELETED',
  BOOK_BORROWED = 'BOOK_BORROWED',
  BOOK_RETURNED = 'BOOK_RETURNED',
  BOOK_LOST = 'BOOK_LOST',

  // Bulk Email actions
  EMAIL_TEMPLATE_CREATED = 'EMAIL_TEMPLATE_CREATED',
  EMAIL_TEMPLATE_UPDATED = 'EMAIL_TEMPLATE_UPDATED',
  EMAIL_TEMPLATE_DELETED = 'EMAIL_TEMPLATE_DELETED',
  EMAIL_CAMPAIGN_CREATED = 'EMAIL_CAMPAIGN_CREATED',
  EMAIL_CAMPAIGN_UPDATED = 'EMAIL_CAMPAIGN_UPDATED',
  EMAIL_CAMPAIGN_DELETED = 'EMAIL_CAMPAIGN_DELETED',
  EMAIL_CAMPAIGN_SENT = 'EMAIL_CAMPAIGN_SENT',
  EMAIL_CAMPAIGN_SCHEDULED = 'EMAIL_CAMPAIGN_SCHEDULED',
  EMAIL_CAMPAIGN_CANCELLED = 'EMAIL_CAMPAIGN_CANCELLED',

  // Form Template actions
  FORM_TEMPLATE_CREATED = 'FORM_TEMPLATE_CREATED',
  FORM_TEMPLATE_UPDATED = 'FORM_TEMPLATE_UPDATED',
  FORM_TEMPLATE_DELETED = 'FORM_TEMPLATE_DELETED',
}

export enum AuditEntity {
  MEMBER = 'MEMBER',
  GROUP = 'GROUP',
  INVENTORY_ITEM = 'INVENTORY_ITEM',
  INVENTORY_CATEGORY = 'INVENTORY_CATEGORY',
  UNIT = 'UNIT',
  MINISTRY = 'MINISTRY',
  SERVICE_REPORT = 'SERVICE_REPORT',
  FIRST_TIMER = 'FIRST_TIMER',
  ATTENDANCE = 'ATTENDANCE',
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  EVENT = 'EVENT',
  EVENT_REGISTRATION = 'EVENT_REGISTRATION',
  // Library entities
  BOOK = 'BOOK',
  BOOK_CATEGORY = 'BOOK_CATEGORY',
  BORROWING = 'BORROWING',
  // Bulk Email entities
  EMAIL_TEMPLATE = 'EMAIL_TEMPLATE',
  EMAIL_CAMPAIGN = 'EMAIL_CAMPAIGN',
  FORM_TEMPLATE = 'FORM_TEMPLATE',
}
