export enum AuditAction {
  // General actions
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  EXPORT = 'EXPORT',

  // Authentication actions
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Member actions
  MEMBER_CREATED = 'MEMBER_CREATED',
  MEMBER_UPDATED = 'MEMBER_UPDATED',
  MEMBER_DELETED = 'MEMBER_DELETED',
  MEMBER_STATUS_CHANGED = 'MEMBER_STATUS_CHANGED',

  // Inventory actions
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_ITEM_DELETED = 'INVENTORY_ITEM_DELETED',
  INVENTORY_STOCK_ADDED = 'INVENTORY_STOCK_ADDED',
  INVENTORY_STOCK_REMOVED = 'INVENTORY_STOCK_REMOVED',
  INVENTORY_ITEM_TRANSFERRED = 'INVENTORY_ITEM_TRANSFERRED',

  // Group/Unit actions
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_UPDATED = 'GROUP_UPDATED',
  GROUP_MEMBER_ADDED = 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED = 'GROUP_MEMBER_REMOVED',

  // Report actions
  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_DOWNLOADED = 'REPORT_DOWNLOADED',

  // Bulk operations
  BULK_IMPORT = 'BULK_IMPORT',
  BULK_UPDATE = 'BULK_UPDATE',
  BULK_DELETE = 'BULK_DELETE',

  // Event actions
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_DELETED = 'EVENT_DELETED',
  EVENT_REGISTRATION_CREATED = 'EVENT_REGISTRATION_CREATED',
  EVENT_REGISTRATION_UPDATED = 'EVENT_REGISTRATION_UPDATED',
  EVENT_CHECK_IN = 'EVENT_CHECK_IN',
}

export enum AuditEntity {
  MEMBER = 'MEMBER',
  GROUP = 'GROUP',
  INVENTORY_ITEM = 'INVENTORY_ITEM',
  INVENTORY_CATEGORY = 'INVENTORY_CATEGORY',
  UNIT = 'UNIT',
  MINISTRY = 'MINISTRY',
  SERVICE_REPORT = 'SERVICE_REPORT',
  FIRST_TIMER = 'FIRST_TIMER',
  ATTENDANCE = 'ATTENDANCE',
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  EVENT = 'EVENT',
  EVENT_REGISTRATION = 'EVENT_REGISTRATION',
}
