export enum InventoryStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DISCONTINUED = 'DISCONTINUED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  LOW_STOCK = 'LOW_STOCK',
}

export enum UnitOfMeasurement {
  // Weight
  GRAMS = 'GRAMS',
  KILOGRAMS = 'KILOGRAMS',
  POUNDS = 'POUNDS',

  // Volume
  MILLILITERS = 'MILLILITERS',
  LITERS = 'LITERS',
  GALLONS = 'GALLONS',

  // Length
  CENTIMETERS = 'CENTIMETERS',
  METERS = 'METERS',
  INCHES = 'INCHES',
  FEET = 'FEET',

  // Quantity
  PIECES = 'PIECES',
  SETS = 'SETS',
  BOXES = 'BOXES',
  PACKAGES = 'PACKAGES',
  BOTTLES = 'BOTTLES',
  CANS = 'CANS',
  BAGS = 'BAGS',

  // Area
  SQUARE_METERS = 'SQUARE_METERS',
  SQUARE_FEET = 'SQUARE_FEET',

  // Other
  HOURS = 'HOURS',
  DAYS = 'DAYS',
  EACH = 'EACH',
}

export enum InventoryMovementType {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  TRANSFER = 'TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  DAMAGE = 'DAMAGE',
  EXPIRED = 'EXPIRED',
  DONATED = 'DONATED',
  SOLD = 'SOLD',
  RETURNED = 'RETURNED',
}

export enum InventoryCategoryType {
  GENERAL = 'GENERAL',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  ELECTRONICS = 'ELECTRONICS',
  FURNITURE = 'FURNITURE',
  BOOKS_MATERIALS = 'BOOKS_MATERIALS',
  FOOD_BEVERAGES = 'FOOD_BEVERAGES',
  CLEANING_SUPPLIES = 'CLEANING_SUPPLIES',
  MEDICAL_SUPPLIES = 'MEDICAL_SUPPLIES',
  MUSICAL_INSTRUMENTS = 'MUSICAL_INSTRUMENTS',
  SOUND_EQUIPMENT = 'SOUND_EQUIPMENT',
  DECORATIONS = 'DECORATIONS',
  UNIFORMS_CLOTHING = 'UNIFORMS_CLOTHING',
  VEHICLES = 'VEHICLES',
  MAINTENANCE = 'MAINTENANCE',
  GIFTS_DONATIONS = 'GIFTS_DONATIONS',
}
