export enum WorkersTrainingStatus {
  REGISTERED = 'REGISTERED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DROPPED_OUT = 'DROPPED_OUT',
  DEFERRED = 'DEFERRED',
  SUSPENDED = 'SUSPENDED',
}

export enum CohortType {
  DAVID_COMPANY = 'DAVID_COMPANY', // DC Training
  LXL_FOUNDATION = 'LXL_FOUNDATION', // Leadership foundation
  LXL_INTERMEDIATE = 'LXL_INTERMEDIATE', // Intermediate leadership
  LXL_ADVANCED = 'LXL_ADVANCED', // Advanced leadership
  PASTORAL_TRAINING = 'PASTORAL_TRAINING', // Pastoral training
  MINISTRY_LEADERSHIP = 'MINISTRY_LEADERSHIP', // Ministry-specific leadership
  SPECIAL_TRAINING = 'SPECIAL_TRAINING', // Special cohorts
}

export enum CohortStatus {
  PLANNING = 'PLANNING',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EXCUSED = 'EXCUSED',
  SICK = 'SICK',
}

export enum AssignmentStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
  LATE_SUBMISSION = 'LATE_SUBMISSION',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
}

export enum TrainingOutcome {
  GRADUATED = 'GRADUATED',
  PROMOTED_TO_DC = 'PROMOTED_TO_DC',
  PROMOTED_TO_LXL = 'PROMOTED_TO_LXL',
  PROMOTED_TO_LEADERSHIP = 'PROMOTED_TO_LEADERSHIP',
  ASSIGNED_TO_UNIT = 'ASSIGNED_TO_UNIT',
  ASSIGNED_TO_MINISTRY = 'ASSIGNED_TO_MINISTRY',
  INCOMPLETE = 'INCOMPLETE',
  FAILED = 'FAILED',
}
